version: "3.8"

services:
  loges01:
    image: opensearchproject/opensearch:2.16.0
    restart: always
    container_name: loges01
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      - node.name=loges01
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=My1Secure_
    ports:
      - 9200:9200
      - 9600:9600
    volumes:
      # Descomentar para persistir datos
      # - esdata01:/usr/share/opensearch/data

  logstash:
    build: ./logstash
    restart: always
    container_name: logstash 
    depends_on:
      - loges01
    ports:
      - 5960:5960/udp

  kibana:
    image: opensearchproject/opensearch-dashboards:2.16.0
    restart: always
    container_name: kibana
    environment:
      - OPENSEARCH_HOSTS=https://loges01:9200
      - OPENSEARCH_USERNAME=admin
      - OPENSEARCH_PASSWORD=My1Secure_
    depends_on:
      - loges01
      - logstash
    ports:
      - 5601:5601
    expose:
      - "5601"

volumes:
  esdata01:
    driver: local
