version: "3.8"

services:
  loges01:
    image: opensearchproject/opensearch:2.16.0
    # build: opensearch
    restart: always
    container_name: loges01
    environment:
      - node.name=loges01
      - discovery.type=single-node
      - cluster.name=es-docker-cluster
      - network.host=0.0.0.0
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
      # - OPENSEARCH_INITIAL_ADMIN_PASSWORD=admin
      
    ports:
      - 9200:9200 # Opensearch
      # - 9600:9600
      # - 5601:5601 # Opensearch Dashboards
    # Descomentar para persistir datos
    # volumes:
      # - esdata01:/usr/share/opensearch/data

  logstash:
    build: ./logstash
    restart: always
    container_name: logstash 
    depends_on:
      - loges01
    ports:
      - 5960:5960/udp

  kibana:
    # image: opensearchproject/opensearch-dashboards:2.16.0
    build: ./opensearch_dashboards
    restart: always
    container_name: kibana
    environment:
      - OPENSEARCH_HOSTS=http://loges01:9200
      # - OPENSEARCH_HOSTS=https://loges01:9200
    depends_on:
      - loges01
      - logstash
    ports:
      - 5601:5601
    expose:
      - "5601"

# volumes:
#   esdata01:
#     driver: local
